spring:
  application:
    name: app
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:devDB
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
    security:
      headers:
        frame=false:

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
