spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
        enabled: always
  server:
    address: 0.0.0.0
    port: ${PORT:8080}
  datasource:
    url: jdbc:h2:mem:mydb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
    security:
      headers:
        frame=false:
