spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_CONNECTION_STRING}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
