spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_CONNECTION_STRING}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
  database-platform: org.hibernate.dialect.MySQLDialect